


CREATE TABLE 'serialized_data' (
'id' INTEGER DEFAULT NULL PRIMARY KEY AUTOINCREMENT REFERENCES 'song' ('id'),
'data' TEXT DEFAULT NULL
);

CREATE TABLE 'song' (
'id' INTEGER DEFAULT NULL PRIMARY KEY AUTOINCREMENT,
'magnet_link' TEXT NOT NULL  DEFAULT 'NULL',
'mbid' TEXT NOT NULL  DEFAULT 'NULL',
UNIQUE (magnet_link)
);


