
ALTER TABLE artist MODIFY `name` VARCHAR(512) CHARACTER SET utf8mb4;
ALTER TABLE release_group MODIFY `title` VARCHAR(512) CHARACTER SET utf8mb4;
ALTER TABLE song MODIFY `title` VARCHAR(512) CHARACTER SET utf8mb4;